nome = str(input('Digite seu nome completo aqui: ')).strip()
nom = nome.upper()
print('O nome em maiúsculas : {}'.format(nom))
nom1 = nome.lower()
print('O nome em minúsculas : {}'.format(nom1))
nom2 = len(nome) - nome.count(' ')
print('Quantas letras : {}'.format(nom2))
nom3 = nome.find(' ')
print('Quantas letras tem o primeiro nome : {}'.format(nom3))